### ISSUE TITLE
Wrong type parameter in building_application.md

### ISSUE THREAD

**Issue by zhiyisun** [Xilinx/SDAccel-Tutorials#10]
In section "**Hardware Execution**" of linked document, 
https://github.com/Xilinx/SDAccel-Tutorials/blob/master/docs/my-first-sdaccel-application/building_application.md

`xocc -t hw_emu --platform xilinx_u200_xdma_201830_1 -g -c -k vadd -I'../src' -o'vadd.xilinx_u200_xdma_201830_1.xo' './src/vadd.cpp'

xocc -t hw_emu --platform xilinx_u200_xdma_201830_1 -g -l --nk vadd:1:vadd_1 -o'vadd.xilinx_u200_xdma_201830_1.xclbin' vadd.xilinx_u200_xdma_201830_1.xo`

should be 

`xocc -t **hw** --platform xilinx_u200_xdma_201830_1 -g -c -k vadd -I'../src' -o'vadd.xilinx_u200_xdma_201830_1.xo' './src/vadd.cpp'

xocc -t **hw** --platform xilinx_u200_xdma_201830_1 -g -l --nk vadd:1:vadd_1 -o'vadd.xilinx_u200_xdma_201830_1.xclbin' vadd.xilinx_u200_xdma_201830_1.xo`

Regards,
Zhiyi

**Comment by ryanvergel** [comment]
Thank you for the feedback! I am looking into this now.

**Comment by ryanvergel** [comment]
![VERGEL288](https://user-images.githubusercontent.com/43358097/61801277-b3faf900-adeb-11e9-9d38-21bdd8efb035.png)

This issue has been resolved.

Thank you!
