### ISSUE TITLE
Issue of "export XCL_EMULATION_MODE sw_emu"

### ISSUE THREAD

**Issue by zhiyisun** [Xilinx/SDAccel-Tutorials#7]
Hello,

In Mixing C++ and RTL Kernels [README](https://github.com/Xilinx/SDAccel-Tutorials/blob/2019.1-Tutorials/docs/mixing-c-rtl-kernels/README.md) , below command might cause problem in some shell. 

`export XCL_EMULATION_MODE sw_emu`

The correct command should be 

`export XCL_EMULATION_MODE=sw_emu`

Regards,
Zhiyi

**Comment by ryanvergel** [comment]
Hello Zhiyi,

Thank you for the input. 

We have modified the code, and 4 instances have been updates with this fix.

Thank you,
-Ryan
